use_frameworks!

target 'Tutorial_Example' do
  pod 'Tutorial', :path => '../'
  pod 'RandomGenerator', '~> 0.1.0', :source => 'git@github.com:cocoaheads-kyiv-14-workshop/specs.git'

  target 'Tutorial_Tests' do
    inherit! :search_paths

    
  end
end
